version: '3.2'

volumes:
  pg-data:
  home-dir:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/app:cached
      - home-dir:/home/user:cached
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - '4001:8080/tcp'
    depends_on:
      - postgres
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"

  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: 'forge'
      POSTGRES_USER: 'forge'
      POSTGRES_PASSWORD: 'forge'
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - 5432
      - '4005:5432/tcp' # Port 4005 for connecting from localhost
